TMS-950: Contact & place-of-business sync fuctionalities
devgeniem/tms-theme-tredu pull request #162
Opened 2023-10-27 08:18 UTC by eebbi

Task: https://geniemdev.atlassian.net/browse/TMS-950

## Description
Add functionalities for new [tms-plugin-contact-sync](https://github.com/devgeniem/tms-plugin-contact-sync) & tms-[plugin-place-of-business-sync](https://github.com/devgeniem/tms-plugin-place-of-business-sync) plugins

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-10-27 12:02 UTC, HPiirainen approved these changes
Kts. huomiot

2023-10-27 12:02 UTC, HPiirainen commented on models/page-contacts.php
> +            'post__in'       => array_map( 'absint', $selected_contacts ),
Saisiko tässäkin kentän mieluummin palauttamaan suoraan ne objektit, niin ei tarvitsisi tehdä uutta queryä?

2023-10-27 12:02 UTC, HPiirainen commented on models/shared/header.php
> +        if ( isset( $current_page->ID ) && (int) $item->object_id === $current_page->ID ) {
```suggestion
        if ( ! empty( $current_page->ID ) && (int) $item->object_id === $current_page->ID ) {
```

2023-10-27 12:02 UTC, HPiirainen commented on partials/shared/contact-item.dust
> +                <p class="m-0">
Vähän hassu että tehdään `<p>` tagi jolta poistetaan marginit, voisi olla myös ihan vaan `<span>` niin ei tule automaattisesti turhia tyylejä 💁‍♂️

2023-11-01 17:36 UTC, eebbi commented on partials/shared/contact-item.dust
> +                <p class="m-0">
`<span>` ei itessään ole "aito" tekstielementti, ja semantiikan näkökulmasta tekisi saman kun aiemmin tuossa olleet tekstiä ympäröivät `<div>` elementit

2023-11-01 18:09 UTC, eebbi commented on lib/ACF/Fields/PlaceOfBusinessFields.php
> +            ->set_instructions( $strings['place_of_business_post']['instructions'] );
Eikös nuo oo jo kunnossa, kun ovat redipress_include_search -funktion sisällä? 👀

2023-11-01 18:09 UTC, eebbi commented on lib/ACF/Fields/PlaceOfBusinessFields.php
> +            ->set_post_types( [ 'placeofbusiness-cpt' ] )
Juu plugarista

2023-11-02 07:27 UTC, HPiirainen commented on lib/ACF/Fields/PlaceOfBusinessFields.php
> +            ->set_instructions( $strings['place_of_business_post']['instructions'] );
Koko putkesta siis kyse.

```
$place_of_business_post_field = ( new Field\Relationship( $strings['place_of_business_post']['label'] ) )
->set_key( "{$key}_place_of_business_post" )
```

-->

```
$place_of_business_post_field = ( new Field\Relationship( $strings['place_of_business_post']['label'] ) )
    ->set_key( "{$key}_place_of_business_post" )
```

2023-11-02 07:33 UTC, eebbi commented on models/page-contacts.php
> +            'post__in'       => array_map( 'absint', $selected_contacts ),
Mitäs meinaat näillä query-kommenteilla? Ei jostain syystä nyt aukee yhtään mulle 😄

2023-11-02 10:03 UTC, HPiirainen requested changes
Tsekkaa vielä noi pari kohtaa

2023-11-02 10:03 UTC, HPiirainen commented on models/page-contacts.php
> +        if ( ! \is_admin() ) {
Tän koko metodin vois tehdä selkeämmin näin:

```
$selected_contacts = \get_field( 'contacts' );
if ( empty( $selected_contacts ) ) {
    return [];
}

$s = \get_query_var( self::SEARCH_QUERY_VAR, false );

// Return all selected contacts if no search was performed.
if ( empty( $s ) ) {
     return $selected_contacts;
}

$args = [
    // ... kaikki query argsit
    's' => $s,
];

$the_query = new \WP_Query( $args );

return $the_query->posts;
```

Eli tehdään early return, jos hakuparametriä ei ole asetettu.

2023-11-02 10:03 UTC, HPiirainen commented on partials/shared/contact.dust
> -<div class="contacts__item column {column_class|attr} has-text-small keep-vertical-spacing">
Eihän joku muu olemassaoleva partial includaa tätä `contact` partialia ja aseta `column_class`ia? Jos ei, niin sit ok poistaa.

2023-11-02 10:18 UTC, eebbi commented on partials/shared/contact.dust
> -<div class="contacts__item column {column_class|attr} has-text-small keep-vertical-spacing">
Eip

2023-11-02 10:59 UTC, HPiirainen approved these changes
👌

2023-11-07 17:35 UTC, merged