TMS-660: Header, footer, navigation
devgeniem/tms-theme-tredu pull request #2
Opened 2022-03-21 08:14 UTC by tim0haapala

CR: [TMS-629](http://geniemdev.atlassian.net/browse/TMS-629)

## Description
Header, footer and navigation styles and accessibility

## Motivation and Context
- TMS-660
- TMS-663
- TMS-659

## How Has This Been Tested?
Local

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

2022-03-22 18:31 UTC, Ahmis commented on assets/styles/settings/brand/_typography.scss
> +        // font-size: 1.1517rem;
Tartteeko tätä, jos kommentoitu pois?

2022-03-22 18:31 UTC, Ahmis commented on assets/styles/settings/brand/_typography.scss
> +        // font-size: 1.1517rem;
Tartteeko tätä, jos kommentoitu pois?

2022-03-22 18:35 UTC, Ahmis commented on models/strings.php
> +                'open_lang_nav'            => 'Avaa kielivalikko, Open language navigation',
Oletan, että nämä käynyt testaajan kautta, mutta eikös nuo tuota ongelmaa, jos luetaan ruudunlukijalla tuo koko teksti, jossa kahta eri kieltä?

2022-03-22 18:35 UTC, Ahmis commented on models/strings.php
> +                'open_lang_nav'            => 'Avaa kielivalikko, Open language navigation',
Oletan, että nämä käynyt testaajan kautta, mutta eikös nuo tuota ongelmaa, jos luetaan ruudunlukijalla tuo koko teksti, jossa kahta eri kieltä?

2022-03-22 18:36 UTC, Ahmis requested changes
Tsekkaa muutamat huomiot.

2022-03-23 08:31 UTC, tim0haapala commented on models/strings.php
> +                'open_lang_nav'            => 'Avaa kielivalikko, Open language navigation',
On joo testaaja katsonut ja siinä tämä korjaus tehtiin. Puitiin tätä yhdessä dailyssä: Mitä jos ei-suomenkielinen tulee pääsivustolle, jossa kieli on suomi ja kuuntelee ruudunlukijalla missä kielivalikon label luetaan "Kielivalikko", niin sitä ei ymmärrä.

2022-03-23 08:33 UTC, tim0haapala commented on assets/styles/settings/brand/_typography.scss
> +        // font-size: 1.1517rem;
Otin pois

2022-03-23 08:33 UTC, tim0haapala commented on assets/styles/helpers/_button.scss
> +$button-border-radius: 0.25rem !default;
Muutettu

2022-03-23 09:02 UTC, tim0haapala commented on models/strings.php
> +                'open_lang_nav'            => 'Avaa kielivalikko, Open language navigation',
Voin toki vaihtaa tämän takaisin, jos niin on parempi

2022-03-23 12:09 UTC, tim0haapala commented on models/strings.php
> +                'open_lang_nav'            => 'Avaa kielivalikko, Open language navigation',
Muutetu nyt takaisin, kuten muissakin TMS:n teemoissa

2022-03-29 08:09 UTC, ville6000 approved these changes

2022-03-29 08:50 UTC, merged