TMS-673: Content page hero
devgeniem/tms-theme-tredu pull request #4
Opened 2022-03-22 10:32 UTC by tim0haapala

CR: [TMS-629](http://geniemdev.atlassian.net/browse/TMS-629)

## Description

Content page hero fields, data and styling

## Motivation and Context

TMS-673

## How Has This Been Tested?
Local, staging

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

2022-03-23 17:26 UTC, Ahmis commented on assets/styles/ui-components/header/_language-nav.scss
> +        width:100%;
Jos tossa width: jälkeen ennen 100% ei oo välilyöntiä, niin sellasen vois lisätä.

2022-03-23 17:29 UTC, Ahmis commented on models/strings.php
> +                'open_lang_nav'            => 'Avaa kielivalikko, Open language navigation',
Näistä juteltiinkin jo aiemmassa PR:ssä.

2022-03-23 17:34 UTC, Ahmis commented on lib/ACF/PageHeroGroup.php
> +     * Register fields
Puuttuu `@return` docblockista.

2022-03-23 17:34 UTC, Ahmis commented on lib/ACF/PageHeroGroup.php
> +     * PageHeroGroup constructor.
Puuttuu `@return` docblockista.

2022-03-23 17:35 UTC, Ahmis commented on lib/ACF/PageHeroGroup.php
> +     *
Puuttuu `@param $key`

2022-03-23 17:35 UTC, Ahmis requested changes
Pari huomiota.

2022-03-24 08:28 UTC, tim0haapala commented on assets/styles/ui-components/header/_language-nav.scss
> +        width:100%;
Muutettu

2022-03-24 08:33 UTC, tim0haapala commented on models/strings.php
> +                'open_lang_nav'            => 'Avaa kielivalikko, Open language navigation',
Muutettu, kuten toisessa PR:ssä

2022-03-24 08:33 UTC, tim0haapala commented on lib/ACF/PageHeroGroup.php
> +     * Register fields
Muutettu

2022-03-24 08:33 UTC, tim0haapala commented on lib/ACF/PageHeroGroup.php
> +     * PageHeroGroup constructor.
Muutettu

2022-03-24 08:33 UTC, tim0haapala commented on lib/ACF/PageHeroGroup.php
> +     *
Muutettu

2022-03-29 08:09 UTC, ville6000 approved these changes

2022-03-29 09:35 UTC, merged